Show user data for newly registered users
luksan47/mars pull request #282
Opened 2020-08-27 18:20 UTC by luksan47

Fixes #203

2020-08-27 21:02 UTC, kdmnk requested changes
If we want this in a separate page, it would be practical to place the approve or deny buttons for this page too. 
And when you click one of them, the next user could appear (useful for mass handling) - but we can open an issue for this.

2020-08-27 21:05 UTC, kdmnk commented on resources/views/admin/user.blade.php
> +                        @endif
The same can be copied to the user page. Please open an issue for this.

2020-08-28 09:37 UTC, luksan47 commented
> If we want this in a separate page, it would be practical to place the approve or deny buttons for this page too.
> And when you click one of them, the next user could appear (useful for mass handling) - but we can open an issue for this.

Added the buttons to the page. Now they redirect back to the list, will open an issue for your suggestion.

Also, there are some code duplicates I don't like. Once we won't be in a hurry, we should remove these.

2020-08-28 15:59 UTC, kdmnk approved these changes
Ok for now.
Please open further issues, including https://github.com/luksan47/mars/pull/282/files#r478695138 and mass handling registrations.

2020-08-28 16:05 UTC, merged