Economic committee module: KKT and Netreg
luksan47/mars pull request #380
Opened 2020-09-25 11:36 UTC by kdmnk

2020-09-26 14:05 UTC, kdmnk commented
Internet activation and policies are missing yet.

2020-09-26 15:20 UTC, kdmnk commented
> Internet activation and policies are missing yet.

hasRole() with object id is still not working as expected, so I used Student Council role without objects.
Should be enough to get it started.

2020-09-27 19:37 UTC, luksan47 commented
To fix the tests, you have to add the routes that can be accessed by anyone to the unsafe routes. There might be some routes that could cause problem and should be skipped, but as I saw, yours are permission issues.

2020-09-27 19:48 UTC, luksan47 requested changes
I have not checked the full PR, but after testing, it looks okay. With the permission checks I'm okay to merge this so we can release tomorrow the most important parts.

Comments:
I am not sure if clicking on the delete button should remove the row from the history. We should always keep the history to verify every transaction.

2020-09-27 19:48 UTC, luksan47 commented on routes/web.php
> +    Route::get('/economic_committee', 'StudentCouncil\EconomicController@index')->name('economic_committee');
This should be grouped under some permission check.

2020-09-27 19:48 UTC, luksan47 commented on routes/web.php
> +    Route::get('/admin/checkout', 'InternetController@showCheckout')->name('admin.checkout');
Check permissions.

2020-09-27 19:52 UTC, luksan47 commented on resources/views/layouts/navbar.blade.php
> +                            <!-- TODO can -->
I think this is okay to be there for everyone involved, but currently it should be disabled as it's not working yet.

2020-09-28 15:18 UTC, kdmnk commented
> I am not sure if clicking on the delete button should remove the row from the history. We should always keep the history to verify every transaction.

I agree. Fortunately, laravel supports soft delete, i switched to that.

2020-09-28 17:47 UTC, luksan47 approved these changes
+1 because of the release

2020-09-28 17:49 UTC, merged