Move checkout to utils
luksan47/mars pull request #461
Opened 2020-10-15 18:15 UTC by luksan47

Fixes #445 

Also simplified a lot of code.

2020-10-19 15:14 UTC, luksan47 commented
After this is merged, before we will have a lot of PR again, I will replace uran-2.x with master as the default branch.

2020-10-21 21:59 UTC, kdmnk commented on app/Models/WorkshopBalance.php
> +        return $payed_residents . ' / ' . $payed_externs . ' (+' . $not_payed . ')';
Note: We might want to consider changing `/` as it can mean division.

2020-10-23 12:41 UTC, luksan47 commented
I will push more changes later.

2020-10-26 20:46 UTC, luksan47 commented
@kdmnk could you have a look?

2020-10-26 22:04 UTC, kdmnk requested changes
Idk if it is a bug here or somewhere else, but the transactions are added to 2020-2021-2 semester (the update workshop balances button is only available on 2020-2021-1 section which is fine).
Please write back the filter which I had to show the semesters only where transactions exists (the page is loading too long this way and the other semesters are unnecessary).
And please add (or use the existing) translations for the payment types.

2020-10-26 22:33 UTC, luksan47 commented
> Idk if it is a bug here or somewhere else, but the transactions are added to 2020-2021-2 semester (the update workshop balances button is only available on 2020-2021-1 section which is fine).

Not sure what's the problem here, will investigate. Might be related to some semester related changes, not coming from this PR.

> Please write back the filter which I had to show the semesters only where transactions exists (the page is loading too long this way and the other semesters are unnecessary).

This would not solve the issue on the long run. Normally, all the semesters we have will have transactions. The root cause of the slowness is #499. I still suggest moving the checkouts and workshop balances to another, 'history' page.

2020-10-26 23:28 UTC, luksan47 commented
> > Idk if it is a bug here or somewhere else, but the transactions are added to 2020-2021-2 semester (the update workshop balances button is only available on 2020-2021-1 section which is fine).
> 
> Not sure what's the problem here, will investigate. Might be related to some semester related changes, not coming from this PR.

Now the future semesters are not shown.

2020-10-26 23:33 UTC, luksan47 commented
> And please add (or use the existing) translations for the payment types.

Done.

2020-10-27 22:02 UTC, bgeree commented
I issued a PR (#508) to the utils branch.
Everything else is in the scope of #499.

2020-10-28 10:01 UTC, luksan47 commented
> > Idk if it is a bug here or somewhere else, but the transactions are added to 2020-2021-2 semester (the update workshop balances button is only available on 2020-2021-1 section which is fine).
> 
> Not sure what's the problem here, will investigate. Might be related to some semester related changes, not coming from this PR.

@kdmnk You might have to run `php artisan cache:clear` to get the correct Semester.

2020-10-29 13:16 UTC, kdmnk approved these changes

2020-10-29 14:21 UTC, merged