issue 416
luksan47/mars pull request #521
Opened 2020-11-23 18:41 UTC by TheBarbaraIsTaken

New policy file for faults:  FaultPolicy.php
registred in AuthServiceProvider.php
changes in FaultController.php according to policies.

2020-12-07 16:54 UTC, kdmnk requested changes
Nice, thanks!
You only need to make the tests work.

2020-12-22 22:41 UTC, luksan47 approved these changes
LGTM. Thanks for fixing this!

2020-12-22 23:02 UTC, kdmnk approved these changes

2020-12-22 23:02 UTC, merged

2020-12-23 09:49 UTC, luksan47 commented
Awesome! @TheBarbaraIsTaken, congrats on your first contribution!