On branch transparentTrnsl
luksan47/mars pull request #523
Opened 2020-11-30 17:46 UTC by Kenzso

Your branch is up to date with 'origin/transparentTrnsl'.

 Changes to be committed:
	modified:   resources/views/localizations/app.blade.php

2020-12-07 16:58 UTC, kdmnk requested changes
Please make the changes as discussed offline.

2020-12-07 18:08 UTC, Kenzso commented
The changes have been made, as we discussed 'offline' :D 
Well, at least I hope this is what we agreed on

2020-12-07 18:14 UTC, kdmnk commented
Yes, thanks! :D

2020-12-22 22:34 UTC, luksan47 approved these changes
LGTM. Thanks for working on this!
Once @kdmnk gives you the +1, we can merge.

2020-12-22 22:34 UTC, luksan47 commented on resources/views/localizations/app.blade.php
> +                    $translations = App\Models\LocalizationContribution::where('language', App::getLocale())->where('key',  $fname.'.'.$key);
Possible optimization: move this (and other php parts) to controller and use eager loading.

2021-01-09 18:44 UTC, Kenzso commented
is this how you do that? I'm sorry, but I am not entirely sure

2021-01-10 13:42 UTC, kdmnk approved these changes
Yes, thanks!

2021-01-10 13:43 UTC, kdmnk commented
@luksan47

2021-01-10 13:45 UTC, merged