Issue #580: Select inits are loaded multiple times
luksan47/mars pull request #581
Opened 2021-05-09 15:25 UTC by luksan47

This might cause slowness on pages with multiple selects, like on the mr and miss page.
Instead of including the scripts multiple times, which has a lot of content (the whole user list), we could load it only once.

This commit adds a `once` attribute to the select component, which would let us load the select init script once per page. Note that this can be used only if we have exactly once type of select on the page, as the other would break, since they won't have the same user list in their init script.

Fixes #580.

2021-05-09 15:26 UTC, luksan47 commented on resources/views/components/input/datepicker.blade.php
> +@include('components.input.init.datepicker')
Note: I also moved these to a different folder just to have all the init scripts out there, but did not thought it necessary to apply the same logic there as well.

2021-05-09 16:18 UTC, kdmnk commented
The js initializer will be applied to all the select elements with the given id.
I'm just thinking if we could handle this feature automatically, without explicitly setting the once flag.
Maybe we can check if the page has already a script for this id or sth like that.
@luksan47 , what do you think?

2021-05-09 17:27 UTC, luksan47 commented
We cannot really do that as this optimization can only be applied when the element lists are the same.

However, now that I think about it, I'm not even sure that my solution is working. For some reasons I thought that the select is initializing all selects, and not only the one with the id. If we are initializing only one ID, we cannot use the once directive. We would have to rewrite the JS code as well, replacing `#<id>` with `.select`.

2021-06-28 21:57 UTC, kdmnk requested changes
Rethink based on the comments above.

2022-03-25 21:41 UTC, luksan47 commented
Please see https://github.com/luksan47/mars#important-notice

2022-03-25 21:41 UTC, closed without merging