Notification mail for new registrations
luksan47/mars pull request #595
Opened 2021-06-29 15:56 UTC by machiato32

Emails go out to the admins and the secretaries.
Added new mail object, blade and a few translations.

2021-06-29 16:04 UTC, kdmnk commented on app/Http/Controllers/Auth/RegisterController.php
> +            Mail::to($secretary)->send(new NewRegistration($secretary->name, $user->name, $user->isCollegist()));
Here passing only $user is enough and then you can handle this in the constructor.

2021-06-29 16:39 UTC, kdmnk requested changes

2021-06-29 16:39 UTC, kdmnk commented on resources/lang/hu/mail.php
> +    'new_registration_tenant' => ':registered_user vendégként regisztrált az Urán rendszerébe. Fogadd el vagy utasítsd vissza a kérelmét.',
Merge these. Collegist/Tenant status can be shown separately.

2021-06-29 16:39 UTC, kdmnk commented on resources/views/emails/new_registration.blade.php
> +    </p>
Add some basic data (status, email, etc.) and a button with a link the corresponding page.

2021-06-29 16:39 UTC, kdmnk commented on app/Mail/NewRegistration.php
> +        $this->is_collegist = $is_collegist;
Here passing only $user is enough. This way you can use the user's other attributes later as well.

2021-06-30 08:08 UTC, kdmnk requested changes
The Staff do not have permission to handle registrations.
You can find this as a Gate in AuthServiceProvider, for now I think its enough to add the Staff to it. @luksan47 will restructure this anyway. (Why are we using Gates instead of policies?)

2021-06-30 08:08 UTC, kdmnk commented on resources/views/emails/new_registration.blade.php
> +@component('mail::button', ['url'=> route('secretariat.registrations.show', ['id' => $user->id])])<!--todo url-->
remove todos

2021-06-30 17:08 UTC, machiato32 commented
Secretaries only see the new registrations of collegists, the staff can handle the teanants' registrations.

2021-06-30 17:12 UTC, machiato32 commented
Accepting and rejecting registrations should only be possible by users with permissions to do so (staff->tenant, secretaries->collegist)

2021-07-01 12:09 UTC, kdmnk commented
@machiato32 
The english hungarian consistency test fails (it might be only a bad ordering, try php artisan locale:sort).


> Accepting and rejecting registrations should only be possible by users with permissions to do so (staff->tenant, secretaries->collegist)

Create a new issue for this, we'll merge this and release.

2021-07-01 12:12 UTC, kdmnk commented
@luksan47 since I cannot test right now, can you test if the staff is able to approve the guests today?
Or we can just release and possibly add a hotfix :D

2021-07-03 06:12 UTC, kdmnk approved these changes

2021-07-03 06:15 UTC, merged